### ISSUE TITLE
Please add a screen shot and a license file

### ISSUE THREAD

**Issue by unixorn** [zhnyuren/zsh-theme-nullzyr#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Also, please add a license, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

**Comment by zhnyuren** [comment]
Thanks for your attention. I'd like to contirbute to open source community very much, but this repository is actually developed for self-use. And I may add some very personal element into it. So it seems that it is not suitable for the public. That's why I did not add any license. If you like this theme, it is a good choice to have a look at [theunraveler](https://github.com/robbyrussell/oh-my-zsh/blob/master/themes/theunraveler.zsh-theme) or [wedisagree](https://github.com/robbyrussell/oh-my-zsh/blob/master/themes/wedisagree.zsh-theme). Actually this theme is based on them. Thanks.

**Comment by unixorn** [comment]
Ok, thanks, I won't include it.
